// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clientes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCliente = `-- name: CreateCliente :one
INSERT INTO clientes (id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
`

type CreateClienteParams struct {
	ID          uuid.UUID             `json:"id"`
	EmpresaID   uuid.UUID             `json:"empresa_id"`
	Nome        string                `json:"nome"`
	Tipo        sql.NullString        `json:"tipo"`
	CpfCnpj     sql.NullString        `json:"cpf_cnpj"`
	Email       sql.NullString        `json:"email"`
	Telefone    sql.NullString        `json:"telefone"`
	Endereco    pqtype.NullRawMessage `json:"endereco"`
	NomeContato sql.NullString        `json:"nome_contato"`
	ErpID       sql.NullString        `json:"erp_id"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, createCliente,
		arg.ID,
		arg.EmpresaID,
		arg.Nome,
		arg.Tipo,
		arg.CpfCnpj,
		arg.Email,
		arg.Telefone,
		arg.Endereco,
		arg.NomeContato,
		arg.ErpID,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.CpfCnpj,
		&i.Email,
		&i.Telefone,
		&i.Endereco,
		&i.NomeContato,
		&i.ErpID,
		&i.ErpSincronizadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteCliente = `-- name: DeleteCliente :exec
UPDATE clientes SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteClienteParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteCliente(ctx context.Context, arg DeleteClienteParams) error {
	_, err := q.db.ExecContext(ctx, deleteCliente, arg.ID, arg.EmpresaID)
	return err
}

const getCliente = `-- name: GetCliente :one
SELECT id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
FROM clientes
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetCliente(ctx context.Context, id uuid.UUID) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getCliente, id)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.CpfCnpj,
		&i.Email,
		&i.Telefone,
		&i.Endereco,
		&i.NomeContato,
		&i.ErpID,
		&i.ErpSincronizadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getClienteByErpID = `-- name: GetClienteByErpID :one
SELECT id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
FROM clientes
WHERE empresa_id = $1 AND erp_id = $2 AND deletado_em IS NULL
`

type GetClienteByErpIDParams struct {
	EmpresaID uuid.UUID      `json:"empresa_id"`
	ErpID     sql.NullString `json:"erp_id"`
}

func (q *Queries) GetClienteByErpID(ctx context.Context, arg GetClienteByErpIDParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getClienteByErpID, arg.EmpresaID, arg.ErpID)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.CpfCnpj,
		&i.Email,
		&i.Telefone,
		&i.Endereco,
		&i.NomeContato,
		&i.ErpID,
		&i.ErpSincronizadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listClientes = `-- name: ListClientes :many
SELECT id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
FROM clientes
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY nome
`

func (q *Queries) ListClientes(ctx context.Context, empresaID uuid.UUID) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, listClientes, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Tipo,
			&i.CpfCnpj,
			&i.Email,
			&i.Telefone,
			&i.Endereco,
			&i.NomeContato,
			&i.ErpID,
			&i.ErpSincronizadoEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClienteErpID = `-- name: UpdateClienteErpID :one
UPDATE clientes
SET erp_id = $2, erp_sincronizado_em = NOW(), atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
`

type UpdateClienteErpIDParams struct {
	ID    uuid.UUID      `json:"id"`
	ErpID sql.NullString `json:"erp_id"`
}

func (q *Queries) UpdateClienteErpID(ctx context.Context, arg UpdateClienteErpIDParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, updateClienteErpID, arg.ID, arg.ErpID)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.CpfCnpj,
		&i.Email,
		&i.Telefone,
		&i.Endereco,
		&i.NomeContato,
		&i.ErpID,
		&i.ErpSincronizadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const updateCliente = `-- name: UpdateCliente :one
UPDATE clientes
SET nome = $2, tipo = $3, cpf_cnpj = $4, email = $5, telefone = $6, endereco = $7, nome_contato = $8, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, tipo, cpf_cnpj, email, telefone, endereco, nome_contato, erp_id, erp_sincronizado_em, criado_em, atualizado_em, deletado_em
`

type UpdateClienteParams struct {
	ID          uuid.UUID             `json:"id"`
	Nome        string                `json:"nome"`
	Tipo        sql.NullString        `json:"tipo"`
	CpfCnpj     sql.NullString        `json:"cpf_cnpj"`
	Email       sql.NullString        `json:"email"`
	Telefone    sql.NullString        `json:"telefone"`
	Endereco    pqtype.NullRawMessage `json:"endereco"`
	NomeContato sql.NullString        `json:"nome_contato"`
}

func (q *Queries) UpdateCliente(ctx context.Context, arg UpdateClienteParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, updateCliente,
		arg.ID,
		arg.Nome,
		arg.Tipo,
		arg.CpfCnpj,
		arg.Email,
		arg.Telefone,
		arg.Endereco,
		arg.NomeContato,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.CpfCnpj,
		&i.Email,
		&i.Telefone,
		&i.Endereco,
		&i.NomeContato,
		&i.ErpID,
		&i.ErpSincronizadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
