// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: empresas.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createEmpresa = `-- name: CreateEmpresa :one
INSERT INTO empresas (id, nome, slug, cnpj, email, telefone, config_erp, config_notificacao)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, nome, slug, cnpj, email, telefone, config_erp, config_notificacao, criado_em, deletado_em
`

type CreateEmpresaParams struct {
	ID                uuid.UUID             `json:"id"`
	Nome              string                `json:"nome"`
	Slug              string                `json:"slug"`
	Cnpj              sql.NullString        `json:"cnpj"`
	Email             sql.NullString        `json:"email"`
	Telefone          sql.NullString        `json:"telefone"`
	ConfigErp         pqtype.NullRawMessage `json:"config_erp"`
	ConfigNotificacao pqtype.NullRawMessage `json:"config_notificacao"`
}

func (q *Queries) CreateEmpresa(ctx context.Context, arg CreateEmpresaParams) (Empresa, error) {
	row := q.db.QueryRowContext(ctx, createEmpresa,
		arg.ID,
		arg.Nome,
		arg.Slug,
		arg.Cnpj,
		arg.Email,
		arg.Telefone,
		arg.ConfigErp,
		arg.ConfigNotificacao,
	)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Slug,
		&i.Cnpj,
		&i.Email,
		&i.Telefone,
		&i.ConfigErp,
		&i.ConfigNotificacao,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteEmpresa = `-- name: DeleteEmpresa :exec
UPDATE empresas SET deletado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) DeleteEmpresa(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmpresa, id)
	return err
}

const getEmpresa = `-- name: GetEmpresa :one
SELECT id, nome, slug, cnpj, email, telefone, config_erp, config_notificacao, criado_em, deletado_em
FROM empresas
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetEmpresa(ctx context.Context, id uuid.UUID) (Empresa, error) {
	row := q.db.QueryRowContext(ctx, getEmpresa, id)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Slug,
		&i.Cnpj,
		&i.Email,
		&i.Telefone,
		&i.ConfigErp,
		&i.ConfigNotificacao,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getEmpresaBySlug = `-- name: GetEmpresaBySlug :one
SELECT id, nome, slug, cnpj, email, telefone, config_erp, config_notificacao, criado_em, deletado_em
FROM empresas
WHERE slug = $1 AND deletado_em IS NULL
`

func (q *Queries) GetEmpresaBySlug(ctx context.Context, slug string) (Empresa, error) {
	row := q.db.QueryRowContext(ctx, getEmpresaBySlug, slug)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Slug,
		&i.Cnpj,
		&i.Email,
		&i.Telefone,
		&i.ConfigErp,
		&i.ConfigNotificacao,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const updateEmpresa = `-- name: UpdateEmpresa :one
UPDATE empresas
SET nome = $2, cnpj = $3, email = $4, telefone = $5, config_erp = $6, config_notificacao = $7
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, nome, slug, cnpj, email, telefone, config_erp, config_notificacao, criado_em, deletado_em
`

type UpdateEmpresaParams struct {
	ID                uuid.UUID             `json:"id"`
	Nome              string                `json:"nome"`
	Cnpj              sql.NullString        `json:"cnpj"`
	Email             sql.NullString        `json:"email"`
	Telefone          sql.NullString        `json:"telefone"`
	ConfigErp         pqtype.NullRawMessage `json:"config_erp"`
	ConfigNotificacao pqtype.NullRawMessage `json:"config_notificacao"`
}

func (q *Queries) UpdateEmpresa(ctx context.Context, arg UpdateEmpresaParams) (Empresa, error) {
	row := q.db.QueryRowContext(ctx, updateEmpresa,
		arg.ID,
		arg.Nome,
		arg.Cnpj,
		arg.Email,
		arg.Telefone,
		arg.ConfigErp,
		arg.ConfigNotificacao,
	)
	var i Empresa
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Slug,
		&i.Cnpj,
		&i.Email,
		&i.Telefone,
		&i.ConfigErp,
		&i.ConfigNotificacao,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
