// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itens_pedido.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createItemPedido = `-- name: CreateItemPedido :one
INSERT INTO itens_pedido (id, empresa_id, pedido_id, produto_id, modelo_id, materia_prima_id, cor, tamanhos_quantidades, quantidade, preco_unitario, tipo_desconto, desconto, total, especificacoes_modelo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, empresa_id, pedido_id, produto_id, modelo_id, materia_prima_id, cor, tamanhos_quantidades, quantidade, preco_unitario, tipo_desconto, desconto, total, especificacoes_modelo, criado_em, atualizado_em, deletado_em
`

type CreateItemPedidoParams struct {
	ID                   uuid.UUID             `json:"id"`
	EmpresaID            uuid.UUID             `json:"empresa_id"`
	PedidoID             uuid.UUID             `json:"pedido_id"`
	ProdutoID            uuid.UUID             `json:"produto_id"`
	ModeloID             uuid.UUID             `json:"modelo_id"`
	MateriaPrimaID       uuid.NullUUID         `json:"materia_prima_id"`
	Cor                  sql.NullString        `json:"cor"`
	TamanhosQuantidades  pqtype.NullRawMessage `json:"tamanhos_quantidades"`
	Quantidade           sql.NullInt32         `json:"quantidade"`
	PrecoUnitario        sql.NullString        `json:"preco_unitario"`
	TipoDesconto         sql.NullString        `json:"tipo_desconto"`
	Desconto             sql.NullString        `json:"desconto"`
	Total                sql.NullString        `json:"total"`
	EspecificacoesModelo pqtype.NullRawMessage `json:"especificacoes_modelo"`
}

func (q *Queries) CreateItemPedido(ctx context.Context, arg CreateItemPedidoParams) (ItensPedido, error) {
	row := q.db.QueryRowContext(ctx, createItemPedido,
		arg.ID,
		arg.EmpresaID,
		arg.PedidoID,
		arg.ProdutoID,
		arg.ModeloID,
		arg.MateriaPrimaID,
		arg.Cor,
		arg.TamanhosQuantidades,
		arg.Quantidade,
		arg.PrecoUnitario,
		arg.TipoDesconto,
		arg.Desconto,
		arg.Total,
		arg.EspecificacoesModelo,
	)
	var i ItensPedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.ProdutoID,
		&i.ModeloID,
		&i.MateriaPrimaID,
		&i.Cor,
		&i.TamanhosQuantidades,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.TipoDesconto,
		&i.Desconto,
		&i.Total,
		&i.EspecificacoesModelo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteItemPedido = `-- name: DeleteItemPedido :exec
UPDATE itens_pedido SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteItemPedidoParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteItemPedido(ctx context.Context, arg DeleteItemPedidoParams) error {
	_, err := q.db.ExecContext(ctx, deleteItemPedido, arg.ID, arg.EmpresaID)
	return err
}

const getItemPedido = `-- name: GetItemPedido :one
SELECT id, empresa_id, pedido_id, produto_id, modelo_id, materia_prima_id, cor, tamanhos_quantidades, quantidade, preco_unitario, tipo_desconto, desconto, total, especificacoes_modelo, criado_em, atualizado_em, deletado_em
FROM itens_pedido
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetItemPedido(ctx context.Context, id uuid.UUID) (ItensPedido, error) {
	row := q.db.QueryRowContext(ctx, getItemPedido, id)
	var i ItensPedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.ProdutoID,
		&i.ModeloID,
		&i.MateriaPrimaID,
		&i.Cor,
		&i.TamanhosQuantidades,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.TipoDesconto,
		&i.Desconto,
		&i.Total,
		&i.EspecificacoesModelo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listItensPorPedido = `-- name: ListItensPorPedido :many
SELECT id, empresa_id, pedido_id, produto_id, modelo_id, materia_prima_id, cor, tamanhos_quantidades, quantidade, preco_unitario, tipo_desconto, desconto, total, especificacoes_modelo, criado_em, atualizado_em, deletado_em
FROM itens_pedido
WHERE pedido_id = $1 AND deletado_em IS NULL
ORDER BY criado_em
`

func (q *Queries) ListItensPorPedido(ctx context.Context, pedidoID uuid.UUID) ([]ItensPedido, error) {
	rows, err := q.db.QueryContext(ctx, listItensPorPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensPedido
	for rows.Next() {
		var i ItensPedido
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.PedidoID,
			&i.ProdutoID,
			&i.ModeloID,
			&i.MateriaPrimaID,
			&i.Cor,
			&i.TamanhosQuantidades,
			&i.Quantidade,
			&i.PrecoUnitario,
			&i.TipoDesconto,
			&i.Desconto,
			&i.Total,
			&i.EspecificacoesModelo,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemPedido = `-- name: UpdateItemPedido :one
UPDATE itens_pedido
SET produto_id = $2, modelo_id = $3, materia_prima_id = $4, cor = $5, tamanhos_quantidades = $6, quantidade = $7, preco_unitario = $8, tipo_desconto = $9, desconto = $10, total = $11, especificacoes_modelo = $12, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, pedido_id, produto_id, modelo_id, materia_prima_id, cor, tamanhos_quantidades, quantidade, preco_unitario, tipo_desconto, desconto, total, especificacoes_modelo, criado_em, atualizado_em, deletado_em
`

type UpdateItemPedidoParams struct {
	ID                   uuid.UUID             `json:"id"`
	ProdutoID            uuid.UUID             `json:"produto_id"`
	ModeloID             uuid.UUID             `json:"modelo_id"`
	MateriaPrimaID       uuid.NullUUID         `json:"materia_prima_id"`
	Cor                  sql.NullString        `json:"cor"`
	TamanhosQuantidades  pqtype.NullRawMessage `json:"tamanhos_quantidades"`
	Quantidade           sql.NullInt32         `json:"quantidade"`
	PrecoUnitario        sql.NullString        `json:"preco_unitario"`
	TipoDesconto         sql.NullString        `json:"tipo_desconto"`
	Desconto             sql.NullString        `json:"desconto"`
	Total                sql.NullString        `json:"total"`
	EspecificacoesModelo pqtype.NullRawMessage `json:"especificacoes_modelo"`
}

func (q *Queries) UpdateItemPedido(ctx context.Context, arg UpdateItemPedidoParams) (ItensPedido, error) {
	row := q.db.QueryRowContext(ctx, updateItemPedido,
		arg.ID,
		arg.ProdutoID,
		arg.ModeloID,
		arg.MateriaPrimaID,
		arg.Cor,
		arg.TamanhosQuantidades,
		arg.Quantidade,
		arg.PrecoUnitario,
		arg.TipoDesconto,
		arg.Desconto,
		arg.Total,
		arg.EspecificacoesModelo,
	)
	var i ItensPedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.ProdutoID,
		&i.ModeloID,
		&i.MateriaPrimaID,
		&i.Cor,
		&i.TamanhosQuantidades,
		&i.Quantidade,
		&i.PrecoUnitario,
		&i.TipoDesconto,
		&i.Desconto,
		&i.Total,
		&i.EspecificacoesModelo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
