// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materias_primas.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMateriaPrima = `-- name: CreateMateriaPrima :one
INSERT INTO materias_primas (id, empresa_id, nome, tipo, cor, composicao, preco)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, empresa_id, nome, tipo, cor, composicao, preco, criado_em, atualizado_em, deletado_em
`

type CreateMateriaPrimaParams struct {
	ID         uuid.UUID      `json:"id"`
	EmpresaID  uuid.UUID      `json:"empresa_id"`
	Nome       string         `json:"nome"`
	Tipo       sql.NullString `json:"tipo"`
	Cor        sql.NullString `json:"cor"`
	Composicao sql.NullString `json:"composicao"`
	Preco      sql.NullString `json:"preco"`
}

func (q *Queries) CreateMateriaPrima(ctx context.Context, arg CreateMateriaPrimaParams) (MateriasPrima, error) {
	row := q.db.QueryRowContext(ctx, createMateriaPrima,
		arg.ID,
		arg.EmpresaID,
		arg.Nome,
		arg.Tipo,
		arg.Cor,
		arg.Composicao,
		arg.Preco,
	)
	var i MateriasPrima
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.Cor,
		&i.Composicao,
		&i.Preco,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteMateriaPrima = `-- name: DeleteMateriaPrima :exec
UPDATE materias_primas SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteMateriaPrimaParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteMateriaPrima(ctx context.Context, arg DeleteMateriaPrimaParams) error {
	_, err := q.db.ExecContext(ctx, deleteMateriaPrima, arg.ID, arg.EmpresaID)
	return err
}

const getMateriaPrima = `-- name: GetMateriaPrima :one
SELECT id, empresa_id, nome, tipo, cor, composicao, preco, criado_em, atualizado_em, deletado_em
FROM materias_primas
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetMateriaPrima(ctx context.Context, id uuid.UUID) (MateriasPrima, error) {
	row := q.db.QueryRowContext(ctx, getMateriaPrima, id)
	var i MateriasPrima
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.Cor,
		&i.Composicao,
		&i.Preco,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listMateriasPrimas = `-- name: ListMateriasPrimas :many
SELECT id, empresa_id, nome, tipo, cor, composicao, preco, criado_em, atualizado_em, deletado_em
FROM materias_primas
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY nome
`

func (q *Queries) ListMateriasPrimas(ctx context.Context, empresaID uuid.UUID) ([]MateriasPrima, error) {
	rows, err := q.db.QueryContext(ctx, listMateriasPrimas, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MateriasPrima
	for rows.Next() {
		var i MateriasPrima
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Tipo,
			&i.Cor,
			&i.Composicao,
			&i.Preco,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMateriaPrima = `-- name: UpdateMateriaPrima :one
UPDATE materias_primas
SET nome = $2, tipo = $3, cor = $4, composicao = $5, preco = $6, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, tipo, cor, composicao, preco, criado_em, atualizado_em, deletado_em
`

type UpdateMateriaPrimaParams struct {
	ID         uuid.UUID      `json:"id"`
	Nome       string         `json:"nome"`
	Tipo       sql.NullString `json:"tipo"`
	Cor        sql.NullString `json:"cor"`
	Composicao sql.NullString `json:"composicao"`
	Preco      sql.NullString `json:"preco"`
}

func (q *Queries) UpdateMateriaPrima(ctx context.Context, arg UpdateMateriaPrimaParams) (MateriasPrima, error) {
	row := q.db.QueryRowContext(ctx, updateMateriaPrima,
		arg.ID,
		arg.Nome,
		arg.Tipo,
		arg.Cor,
		arg.Composicao,
		arg.Preco,
	)
	var i MateriasPrima
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Tipo,
		&i.Cor,
		&i.Composicao,
		&i.Preco,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
