// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Cliente struct {
	ID                uuid.UUID             `json:"id"`
	EmpresaID         uuid.UUID             `json:"empresa_id"`
	Nome              string                `json:"nome"`
	Tipo              sql.NullString        `json:"tipo"`
	CpfCnpj           sql.NullString        `json:"cpf_cnpj"`
	Email             sql.NullString        `json:"email"`
	Telefone          sql.NullString        `json:"telefone"`
	Endereco          pqtype.NullRawMessage `json:"endereco"`
	NomeContato       sql.NullString        `json:"nome_contato"`
	ErpID             sql.NullString        `json:"erp_id"`
	ErpSincronizadoEm sql.NullTime          `json:"erp_sincronizado_em"`
	CriadoEm          sql.NullTime          `json:"criado_em"`
	AtualizadoEm      sql.NullTime          `json:"atualizado_em"`
	DeletadoEm        sql.NullTime          `json:"deletado_em"`
}

type ConfigsEtapaProducao struct {
	ID              uuid.UUID      `json:"id"`
	EmpresaID       uuid.UUID      `json:"empresa_id"`
	Nome            string         `json:"nome"`
	Descricao       sql.NullString `json:"descricao"`
	Ordem           int32          `json:"ordem"`
	PercentualTempo sql.NullInt32  `json:"percentual_tempo"`
	CriadoEm        sql.NullTime   `json:"criado_em"`
	DeletadoEm      sql.NullTime   `json:"deletado_em"`
}

type Empresa struct {
	ID                uuid.UUID             `json:"id"`
	Nome              string                `json:"nome"`
	Slug              string                `json:"slug"`
	Cnpj              sql.NullString        `json:"cnpj"`
	Email             sql.NullString        `json:"email"`
	Telefone          sql.NullString        `json:"telefone"`
	ConfigErp         pqtype.NullRawMessage `json:"config_erp"`
	ConfigNotificacao pqtype.NullRawMessage `json:"config_notificacao"`
	CriadoEm          sql.NullTime          `json:"criado_em"`
	DeletadoEm        sql.NullTime          `json:"deletado_em"`
}

type EtapasProducao struct {
	ID                uuid.UUID      `json:"id"`
	OrdemProducaoID   uuid.UUID      `json:"ordem_producao_id"`
	ConfigEtapaID     uuid.UUID      `json:"config_etapa_id"`
	Status            sql.NullString `json:"status"`
	Responsavel       uuid.NullUUID  `json:"responsavel"`
	PrevisaoConclusao sql.NullTime   `json:"previsao_conclusao"`
	DataInicio        sql.NullTime   `json:"data_inicio"`
	IniciadoEm        sql.NullTime   `json:"iniciado_em"`
	DataConclusao     sql.NullTime   `json:"data_conclusao"`
	FinalizadoEm      sql.NullTime   `json:"finalizado_em"`
	DeletadoEm        sql.NullTime   `json:"deletado_em"`
}

type ItensPedido struct {
	ID                   uuid.UUID             `json:"id"`
	EmpresaID            uuid.UUID             `json:"empresa_id"`
	PedidoID             uuid.UUID             `json:"pedido_id"`
	ProdutoID            uuid.UUID             `json:"produto_id"`
	ModeloID             uuid.UUID             `json:"modelo_id"`
	MateriaPrimaID       uuid.NullUUID         `json:"materia_prima_id"`
	Cor                  sql.NullString        `json:"cor"`
	TamanhosQuantidades  pqtype.NullRawMessage `json:"tamanhos_quantidades"`
	Quantidade           sql.NullInt32         `json:"quantidade"`
	PrecoUnitario        sql.NullString        `json:"preco_unitario"`
	TipoDesconto         sql.NullString        `json:"tipo_desconto"`
	Desconto             sql.NullString        `json:"desconto"`
	Total                sql.NullString        `json:"total"`
	EspecificacoesModelo pqtype.NullRawMessage `json:"especificacoes_modelo"`
	CriadoEm             sql.NullTime          `json:"criado_em"`
	AtualizadoEm         sql.NullTime          `json:"atualizado_em"`
	DeletadoEm           sql.NullTime          `json:"deletado_em"`
}

type LogsAuditorium struct {
	ID              uuid.UUID             `json:"id"`
	EmpresaID       uuid.UUID             `json:"empresa_id"`
	UsuarioID       uuid.NullUUID         `json:"usuario_id"`
	Acao            string                `json:"acao"`
	Entidade        string                `json:"entidade"`
	EntidadeID      uuid.NullUUID         `json:"entidade_id"`
	DadosAnteriores pqtype.NullRawMessage `json:"dados_anteriores"`
	DadosNovos      pqtype.NullRawMessage `json:"dados_novos"`
	CriadoEm        sql.NullTime          `json:"criado_em"`
}

type MateriasPrima struct {
	ID           uuid.UUID      `json:"id"`
	EmpresaID    uuid.UUID      `json:"empresa_id"`
	Nome         string         `json:"nome"`
	Tipo         sql.NullString `json:"tipo"`
	Cor          sql.NullString `json:"cor"`
	Composicao   sql.NullString `json:"composicao"`
	Preco        sql.NullString `json:"preco"`
	CriadoEm     sql.NullTime   `json:"criado_em"`
	AtualizadoEm sql.NullTime   `json:"atualizado_em"`
	DeletadoEm   sql.NullTime   `json:"deletado_em"`
}

type Modelo struct {
	ID              uuid.UUID      `json:"id"`
	EmpresaID       uuid.UUID      `json:"empresa_id"`
	ProdutoID       uuid.UUID      `json:"produto_id"`
	Nome            string         `json:"nome"`
	UrlImagemFrente sql.NullString `json:"url_imagem_frente"`
	UrlImagemVerso  sql.NullString `json:"url_imagem_verso"`
	Tipo            sql.NullString `json:"tipo"`
	Gola            sql.NullString `json:"gola"`
	Mangas          sql.NullString `json:"mangas"`
	Barras          sql.NullString `json:"barras"`
	Recortes        sql.NullString `json:"recortes"`
	Bolsos          sql.NullString `json:"bolsos"`
	Acabamento      sql.NullString `json:"acabamento"`
	CriadoEm        sql.NullTime   `json:"criado_em"`
	AtualizadoEm    sql.NullTime   `json:"atualizado_em"`
	DeletadoEm      sql.NullTime   `json:"deletado_em"`
}

type OrdensProducao struct {
	ID           uuid.UUID      `json:"id"`
	EmpresaID    uuid.UUID      `json:"empresa_id"`
	PedidoID     uuid.UUID      `json:"pedido_id"`
	Status       sql.NullString `json:"status"`
	IniciadoEm   sql.NullTime   `json:"iniciado_em"`
	FinalizadoEm sql.NullTime   `json:"finalizado_em"`
	CriadoEm     sql.NullTime   `json:"criado_em"`
	DeletadoEm   sql.NullTime   `json:"deletado_em"`
}

type Pedido struct {
	ID              uuid.UUID      `json:"id"`
	EmpresaID       uuid.UUID      `json:"empresa_id"`
	Numero          int32          `json:"numero"`
	ClienteID       uuid.NullUUID  `json:"cliente_id"`
	VendedorID      uuid.NullUUID  `json:"vendedor_id"`
	CriadoPor       uuid.NullUUID  `json:"criado_por"`
	Status          sql.NullString `json:"status"`
	Observacoes     sql.NullString `json:"observacoes"`
	Total           sql.NullString `json:"total"`
	FormaPagamento  sql.NullString `json:"forma_pagamento"`
	PrevisaoEntrega sql.NullTime   `json:"previsao_entrega"`
	DataEntrega     sql.NullTime   `json:"data_entrega"`
	CriadoEm        sql.NullTime   `json:"criado_em"`
	AtualizadoEm    sql.NullTime   `json:"atualizado_em"`
	DeletadoEm      sql.NullTime   `json:"deletado_em"`
}

type PedidosContadore struct {
	EmpresaID    uuid.UUID `json:"empresa_id"`
	UltimoNumero int32     `json:"ultimo_numero"`
}

type Personalizaco struct {
	ID            uuid.UUID             `json:"id"`
	EmpresaID     uuid.UUID             `json:"empresa_id"`
	ItemPedidoID  uuid.UUID             `json:"item_pedido_id"`
	Tipo          sql.NullString        `json:"tipo"`
	Cores         pqtype.NullRawMessage `json:"cores"`
	TipoConteudo  sql.NullString        `json:"tipo_conteudo"`
	UrlImagem     sql.NullString        `json:"url_imagem"`
	TextoConteudo sql.NullString        `json:"texto_conteudo"`
	TextoFonte    sql.NullString        `json:"texto_fonte"`
	Lado          sql.NullString        `json:"lado"`
	Localizacao   sql.NullString        `json:"localizacao"`
	CanvasX       sql.NullFloat64       `json:"canvas_x"`
	CanvasY       sql.NullFloat64       `json:"canvas_y"`
	CanvasEscala  sql.NullFloat64       `json:"canvas_escala"`
	CanvasRotacao sql.NullFloat64       `json:"canvas_rotacao"`
	CanvasLargura sql.NullInt32         `json:"canvas_largura"`
	CanvasAltura  sql.NullInt32         `json:"canvas_altura"`
	Observacao    sql.NullString        `json:"observacao"`
	DeletadoEm    sql.NullTime          `json:"deletado_em"`
}

type Produto struct {
	ID               uuid.UUID       `json:"id"`
	EmpresaID        uuid.UUID       `json:"empresa_id"`
	Nome             string          `json:"nome"`
	Descricao        sql.NullString  `json:"descricao"`
	UrlImagem        sql.NullString  `json:"url_imagem"`
	ConsumoPorUnidade sql.NullFloat64 `json:"consumo_por_unidade"`
	UnidadeConsumo   sql.NullString  `json:"unidade_consumo"`
	CriadoEm        sql.NullTime    `json:"criado_em"`
	AtualizadoEm    sql.NullTime    `json:"atualizado_em"`
	DeletadoEm      sql.NullTime    `json:"deletado_em"`
}

type Usuario struct {
	ID         uuid.UUID      `json:"id"`
	EmpresaID  uuid.UUID      `json:"empresa_id"`
	Nome       string         `json:"nome"`
	Email      string         `json:"email"`
	Perfil     sql.NullString `json:"perfil"`
	CriadoEm   sql.NullTime   `json:"criado_em"`
	DeletadoEm sql.NullTime   `json:"deletado_em"`
}

type VersoesItemPedido struct {
	ID           uuid.UUID       `json:"id"`
	ItemPedidoID uuid.UUID       `json:"item_pedido_id"`
	NumeroVersao int32           `json:"numero_versao"`
	Snapshot     json.RawMessage `json:"snapshot"`
	AlteradoPor  uuid.NullUUID   `json:"alterado_por"`
	CriadoEm     sql.NullTime    `json:"criado_em"`
}
