// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modelos.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createModelo = `-- name: CreateModelo :one
INSERT INTO modelos (id, empresa_id, produto_id, nome, url_imagem_frente, url_imagem_verso, tipo, gola, mangas, barras, recortes, bolsos, acabamento)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, empresa_id, produto_id, nome, url_imagem_frente, url_imagem_verso, tipo, gola, mangas, barras, recortes, bolsos, acabamento, criado_em, atualizado_em, deletado_em
`

type CreateModeloParams struct {
	ID              uuid.UUID      `json:"id"`
	EmpresaID       uuid.UUID      `json:"empresa_id"`
	ProdutoID       uuid.UUID      `json:"produto_id"`
	Nome            string         `json:"nome"`
	UrlImagemFrente sql.NullString `json:"url_imagem_frente"`
	UrlImagemVerso  sql.NullString `json:"url_imagem_verso"`
	Tipo            sql.NullString `json:"tipo"`
	Gola            sql.NullString `json:"gola"`
	Mangas          sql.NullString `json:"mangas"`
	Barras          sql.NullString `json:"barras"`
	Recortes        sql.NullString `json:"recortes"`
	Bolsos          sql.NullString `json:"bolsos"`
	Acabamento      sql.NullString `json:"acabamento"`
}

func (q *Queries) CreateModelo(ctx context.Context, arg CreateModeloParams) (Modelo, error) {
	row := q.db.QueryRowContext(ctx, createModelo,
		arg.ID,
		arg.EmpresaID,
		arg.ProdutoID,
		arg.Nome,
		arg.UrlImagemFrente,
		arg.UrlImagemVerso,
		arg.Tipo,
		arg.Gola,
		arg.Mangas,
		arg.Barras,
		arg.Recortes,
		arg.Bolsos,
		arg.Acabamento,
	)
	var i Modelo
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ProdutoID,
		&i.Nome,
		&i.UrlImagemFrente,
		&i.UrlImagemVerso,
		&i.Tipo,
		&i.Gola,
		&i.Mangas,
		&i.Barras,
		&i.Recortes,
		&i.Bolsos,
		&i.Acabamento,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteModelo = `-- name: DeleteModelo :exec
UPDATE modelos SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteModeloParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteModelo(ctx context.Context, arg DeleteModeloParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelo, arg.ID, arg.EmpresaID)
	return err
}

const getModelo = `-- name: GetModelo :one
SELECT id, empresa_id, produto_id, nome, url_imagem_frente, url_imagem_verso, tipo, gola, mangas, barras, recortes, bolsos, acabamento, criado_em, atualizado_em, deletado_em
FROM modelos
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetModelo(ctx context.Context, id uuid.UUID) (Modelo, error) {
	row := q.db.QueryRowContext(ctx, getModelo, id)
	var i Modelo
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ProdutoID,
		&i.Nome,
		&i.UrlImagemFrente,
		&i.UrlImagemVerso,
		&i.Tipo,
		&i.Gola,
		&i.Mangas,
		&i.Barras,
		&i.Recortes,
		&i.Bolsos,
		&i.Acabamento,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listModelos = `-- name: ListModelos :many
SELECT id, empresa_id, produto_id, nome, url_imagem_frente, url_imagem_verso, tipo, gola, mangas, barras, recortes, bolsos, acabamento, criado_em, atualizado_em, deletado_em
FROM modelos
WHERE empresa_id = $1 AND produto_id = $2 AND deletado_em IS NULL
ORDER BY nome
`

type ListModelosParams struct {
	EmpresaID uuid.UUID `json:"empresa_id"`
	ProdutoID uuid.UUID `json:"produto_id"`
}

func (q *Queries) ListModelos(ctx context.Context, arg ListModelosParams) ([]Modelo, error) {
	rows, err := q.db.QueryContext(ctx, listModelos, arg.EmpresaID, arg.ProdutoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modelo
	for rows.Next() {
		var i Modelo
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.ProdutoID,
			&i.Nome,
			&i.UrlImagemFrente,
			&i.UrlImagemVerso,
			&i.Tipo,
			&i.Gola,
			&i.Mangas,
			&i.Barras,
			&i.Recortes,
			&i.Bolsos,
			&i.Acabamento,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelo = `-- name: UpdateModelo :one
UPDATE modelos
SET nome = $2, url_imagem_frente = $3, url_imagem_verso = $4, tipo = $5, gola = $6, mangas = $7, barras = $8, recortes = $9, bolsos = $10, acabamento = $11, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, produto_id, nome, url_imagem_frente, url_imagem_verso, tipo, gola, mangas, barras, recortes, bolsos, acabamento, criado_em, atualizado_em, deletado_em
`

type UpdateModeloParams struct {
	ID              uuid.UUID      `json:"id"`
	Nome            string         `json:"nome"`
	UrlImagemFrente sql.NullString `json:"url_imagem_frente"`
	UrlImagemVerso  sql.NullString `json:"url_imagem_verso"`
	Tipo            sql.NullString `json:"tipo"`
	Gola            sql.NullString `json:"gola"`
	Mangas          sql.NullString `json:"mangas"`
	Barras          sql.NullString `json:"barras"`
	Recortes        sql.NullString `json:"recortes"`
	Bolsos          sql.NullString `json:"bolsos"`
	Acabamento      sql.NullString `json:"acabamento"`
}

func (q *Queries) UpdateModelo(ctx context.Context, arg UpdateModeloParams) (Modelo, error) {
	row := q.db.QueryRowContext(ctx, updateModelo,
		arg.ID,
		arg.Nome,
		arg.UrlImagemFrente,
		arg.UrlImagemVerso,
		arg.Tipo,
		arg.Gola,
		arg.Mangas,
		arg.Barras,
		arg.Recortes,
		arg.Bolsos,
		arg.Acabamento,
	)
	var i Modelo
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ProdutoID,
		&i.Nome,
		&i.UrlImagemFrente,
		&i.UrlImagemVerso,
		&i.Tipo,
		&i.Gola,
		&i.Mangas,
		&i.Barras,
		&i.Recortes,
		&i.Bolsos,
		&i.Acabamento,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
