// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pedidos.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPedido = `-- name: CreatePedido :one
INSERT INTO pedidos (id, empresa_id, numero, cliente_id, vendedor_id, criado_por, status, observacoes, forma_pagamento, previsao_entrega)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, empresa_id, numero, cliente_id, vendedor_id, criado_por, status, observacoes, total, forma_pagamento, previsao_entrega, data_entrega, criado_em, atualizado_em, deletado_em
`

type CreatePedidoParams struct {
	ID              uuid.UUID      `json:"id"`
	EmpresaID       uuid.UUID      `json:"empresa_id"`
	Numero          int32          `json:"numero"`
	ClienteID       uuid.NullUUID  `json:"cliente_id"`
	VendedorID      uuid.NullUUID  `json:"vendedor_id"`
	CriadoPor       uuid.NullUUID  `json:"criado_por"`
	Status          sql.NullString `json:"status"`
	Observacoes     sql.NullString `json:"observacoes"`
	FormaPagamento  sql.NullString `json:"forma_pagamento"`
	PrevisaoEntrega sql.NullTime   `json:"previsao_entrega"`
}

func (q *Queries) CreatePedido(ctx context.Context, arg CreatePedidoParams) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, createPedido,
		arg.ID,
		arg.EmpresaID,
		arg.Numero,
		arg.ClienteID,
		arg.VendedorID,
		arg.CriadoPor,
		arg.Status,
		arg.Observacoes,
		arg.FormaPagamento,
		arg.PrevisaoEntrega,
	)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Numero,
		&i.ClienteID,
		&i.VendedorID,
		&i.CriadoPor,
		&i.Status,
		&i.Observacoes,
		&i.Total,
		&i.FormaPagamento,
		&i.PrevisaoEntrega,
		&i.DataEntrega,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deletePedido = `-- name: DeletePedido :exec
UPDATE pedidos SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeletePedidoParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeletePedido(ctx context.Context, arg DeletePedidoParams) error {
	_, err := q.db.ExecContext(ctx, deletePedido, arg.ID, arg.EmpresaID)
	return err
}

const getPedido = `-- name: GetPedido :one
SELECT id, empresa_id, numero, cliente_id, vendedor_id, criado_por, status, observacoes, total, forma_pagamento, previsao_entrega, data_entrega, criado_em, atualizado_em, deletado_em
FROM pedidos
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetPedido(ctx context.Context, id uuid.UUID) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, getPedido, id)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Numero,
		&i.ClienteID,
		&i.VendedorID,
		&i.CriadoPor,
		&i.Status,
		&i.Observacoes,
		&i.Total,
		&i.FormaPagamento,
		&i.PrevisaoEntrega,
		&i.DataEntrega,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const initNumeroPedido = `-- name: InitNumeroPedido :one
INSERT INTO pedidos_contadores (empresa_id, ultimo_numero)
VALUES ($1, 1)
ON CONFLICT (empresa_id) DO UPDATE SET ultimo_numero = pedidos_contadores.ultimo_numero + 1
RETURNING ultimo_numero
`

func (q *Queries) InitNumeroPedido(ctx context.Context, empresaID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, initNumeroPedido, empresaID)
	var ultimo_numero int32
	err := row.Scan(&ultimo_numero)
	return ultimo_numero, err
}

const listPedidos = `-- name: ListPedidos :many
SELECT id, empresa_id, numero, cliente_id, vendedor_id, criado_por, status, observacoes, total, forma_pagamento, previsao_entrega, data_entrega, criado_em, atualizado_em, deletado_em
FROM pedidos
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY numero DESC
`

func (q *Queries) ListPedidos(ctx context.Context, empresaID uuid.UUID) ([]Pedido, error) {
	rows, err := q.db.QueryContext(ctx, listPedidos, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pedido
	for rows.Next() {
		var i Pedido
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Numero,
			&i.ClienteID,
			&i.VendedorID,
			&i.CriadoPor,
			&i.Status,
			&i.Observacoes,
			&i.Total,
			&i.FormaPagamento,
			&i.PrevisaoEntrega,
			&i.DataEntrega,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextNumeroPedido = `-- name: NextNumeroPedido :one
UPDATE pedidos_contadores
SET ultimo_numero = ultimo_numero + 1
WHERE empresa_id = $1
RETURNING ultimo_numero
`

func (q *Queries) NextNumeroPedido(ctx context.Context, empresaID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextNumeroPedido, empresaID)
	var ultimo_numero int32
	err := row.Scan(&ultimo_numero)
	return ultimo_numero, err
}

const updatePedidoStatus = `-- name: UpdatePedidoStatus :one
UPDATE pedidos
SET status = $2, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, numero, cliente_id, vendedor_id, criado_por, status, observacoes, total, forma_pagamento, previsao_entrega, data_entrega, criado_em, atualizado_em, deletado_em
`

type UpdatePedidoStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdatePedidoStatus(ctx context.Context, arg UpdatePedidoStatusParams) (Pedido, error) {
	row := q.db.QueryRowContext(ctx, updatePedidoStatus, arg.ID, arg.Status)
	var i Pedido
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Numero,
		&i.ClienteID,
		&i.VendedorID,
		&i.CriadoPor,
		&i.Status,
		&i.Observacoes,
		&i.Total,
		&i.FormaPagamento,
		&i.PrevisaoEntrega,
		&i.DataEntrega,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
