// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personalizacoes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPersonalizacao = `-- name: CreatePersonalizacao :one
INSERT INTO personalizacoes (id, empresa_id, item_pedido_id, tipo, cores, tipo_conteudo, url_imagem, texto_conteudo, texto_fonte, lado, localizacao, canvas_x, canvas_y, canvas_escala, canvas_rotacao, canvas_largura, canvas_altura, observacao)
VALUES ($1, $2, $3, $4, $5::jsonb, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, empresa_id, item_pedido_id, tipo, cores, tipo_conteudo, url_imagem, texto_conteudo, texto_fonte, lado, localizacao, canvas_x, canvas_y, canvas_escala, canvas_rotacao, canvas_largura, canvas_altura, observacao, deletado_em
`

type CreatePersonalizacaoParams struct {
	ID            uuid.UUID             `json:"id"`
	EmpresaID     uuid.UUID             `json:"empresa_id"`
	ItemPedidoID  uuid.UUID             `json:"item_pedido_id"`
	Tipo          sql.NullString        `json:"tipo"`
	Cores         pqtype.NullRawMessage `json:"cores"`
	TipoConteudo  sql.NullString        `json:"tipo_conteudo"`
	UrlImagem     sql.NullString        `json:"url_imagem"`
	TextoConteudo sql.NullString        `json:"texto_conteudo"`
	TextoFonte    sql.NullString        `json:"texto_fonte"`
	Lado          sql.NullString        `json:"lado"`
	Localizacao   sql.NullString        `json:"localizacao"`
	CanvasX       sql.NullFloat64       `json:"canvas_x"`
	CanvasY       sql.NullFloat64       `json:"canvas_y"`
	CanvasEscala  sql.NullFloat64       `json:"canvas_escala"`
	CanvasRotacao sql.NullFloat64       `json:"canvas_rotacao"`
	CanvasLargura sql.NullInt32         `json:"canvas_largura"`
	CanvasAltura  sql.NullInt32         `json:"canvas_altura"`
	Observacao    sql.NullString        `json:"observacao"`
}

func (q *Queries) CreatePersonalizacao(ctx context.Context, arg CreatePersonalizacaoParams) (Personalizaco, error) {
	row := q.db.QueryRowContext(ctx, createPersonalizacao,
		arg.ID,
		arg.EmpresaID,
		arg.ItemPedidoID,
		arg.Tipo,
		arg.Cores,
		arg.TipoConteudo,
		arg.UrlImagem,
		arg.TextoConteudo,
		arg.TextoFonte,
		arg.Lado,
		arg.Localizacao,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasEscala,
		arg.CanvasRotacao,
		arg.CanvasLargura,
		arg.CanvasAltura,
		arg.Observacao,
	)
	var i Personalizaco
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ItemPedidoID,
		&i.Tipo,
		&i.Cores,
		&i.TipoConteudo,
		&i.UrlImagem,
		&i.TextoConteudo,
		&i.TextoFonte,
		&i.Lado,
		&i.Localizacao,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasEscala,
		&i.CanvasRotacao,
		&i.CanvasLargura,
		&i.CanvasAltura,
		&i.Observacao,
		&i.DeletadoEm,
	)
	return i, err
}

const deletePersonalizacao = `-- name: DeletePersonalizacao :exec
UPDATE personalizacoes SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeletePersonalizacaoParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeletePersonalizacao(ctx context.Context, arg DeletePersonalizacaoParams) error {
	_, err := q.db.ExecContext(ctx, deletePersonalizacao, arg.ID, arg.EmpresaID)
	return err
}

const getPersonalizacao = `-- name: GetPersonalizacao :one
SELECT id, empresa_id, item_pedido_id, tipo, cores, tipo_conteudo, url_imagem, texto_conteudo, texto_fonte, lado, localizacao, canvas_x, canvas_y, canvas_escala, canvas_rotacao, canvas_largura, canvas_altura, observacao, deletado_em
FROM personalizacoes
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetPersonalizacao(ctx context.Context, id uuid.UUID) (Personalizaco, error) {
	row := q.db.QueryRowContext(ctx, getPersonalizacao, id)
	var i Personalizaco
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ItemPedidoID,
		&i.Tipo,
		&i.Cores,
		&i.TipoConteudo,
		&i.UrlImagem,
		&i.TextoConteudo,
		&i.TextoFonte,
		&i.Lado,
		&i.Localizacao,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasEscala,
		&i.CanvasRotacao,
		&i.CanvasLargura,
		&i.CanvasAltura,
		&i.Observacao,
		&i.DeletadoEm,
	)
	return i, err
}

const listPersonalizacoesPorItem = `-- name: ListPersonalizacoesPorItem :many
SELECT id, empresa_id, item_pedido_id, tipo, cores, tipo_conteudo, url_imagem, texto_conteudo, texto_fonte, lado, localizacao, canvas_x, canvas_y, canvas_escala, canvas_rotacao, canvas_largura, canvas_altura, observacao, deletado_em
FROM personalizacoes
WHERE item_pedido_id = $1 AND deletado_em IS NULL
`

func (q *Queries) ListPersonalizacoesPorItem(ctx context.Context, itemPedidoID uuid.UUID) ([]Personalizaco, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalizacoesPorItem, itemPedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Personalizaco
	for rows.Next() {
		var i Personalizaco
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.ItemPedidoID,
			&i.Tipo,
			&i.Cores,
			&i.TipoConteudo,
			&i.UrlImagem,
			&i.TextoConteudo,
			&i.TextoFonte,
			&i.Lado,
			&i.Localizacao,
			&i.CanvasX,
			&i.CanvasY,
			&i.CanvasEscala,
			&i.CanvasRotacao,
			&i.CanvasLargura,
			&i.CanvasAltura,
			&i.Observacao,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonalizacao = `-- name: UpdatePersonalizacao :one
UPDATE personalizacoes
SET tipo = $2, cores = $3::jsonb, tipo_conteudo = $4, url_imagem = $5, texto_conteudo = $6, texto_fonte = $7, lado = $8, localizacao = $9, canvas_x = $10, canvas_y = $11, canvas_escala = $12, canvas_rotacao = $13, canvas_largura = $14, canvas_altura = $15, observacao = $16
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, item_pedido_id, tipo, cores, tipo_conteudo, url_imagem, texto_conteudo, texto_fonte, lado, localizacao, canvas_x, canvas_y, canvas_escala, canvas_rotacao, canvas_largura, canvas_altura, observacao, deletado_em
`

type UpdatePersonalizacaoParams struct {
	ID            uuid.UUID             `json:"id"`
	Tipo          sql.NullString        `json:"tipo"`
	Cores         pqtype.NullRawMessage `json:"cores"`
	TipoConteudo  sql.NullString        `json:"tipo_conteudo"`
	UrlImagem     sql.NullString        `json:"url_imagem"`
	TextoConteudo sql.NullString        `json:"texto_conteudo"`
	TextoFonte    sql.NullString        `json:"texto_fonte"`
	Lado          sql.NullString        `json:"lado"`
	Localizacao   sql.NullString        `json:"localizacao"`
	CanvasX       sql.NullFloat64       `json:"canvas_x"`
	CanvasY       sql.NullFloat64       `json:"canvas_y"`
	CanvasEscala  sql.NullFloat64       `json:"canvas_escala"`
	CanvasRotacao sql.NullFloat64       `json:"canvas_rotacao"`
	CanvasLargura sql.NullInt32         `json:"canvas_largura"`
	CanvasAltura  sql.NullInt32         `json:"canvas_altura"`
	Observacao    sql.NullString        `json:"observacao"`
}

func (q *Queries) UpdatePersonalizacao(ctx context.Context, arg UpdatePersonalizacaoParams) (Personalizaco, error) {
	row := q.db.QueryRowContext(ctx, updatePersonalizacao,
		arg.ID,
		arg.Tipo,
		arg.Cores,
		arg.TipoConteudo,
		arg.UrlImagem,
		arg.TextoConteudo,
		arg.TextoFonte,
		arg.Lado,
		arg.Localizacao,
		arg.CanvasX,
		arg.CanvasY,
		arg.CanvasEscala,
		arg.CanvasRotacao,
		arg.CanvasLargura,
		arg.CanvasAltura,
		arg.Observacao,
	)
	var i Personalizaco
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.ItemPedidoID,
		&i.Tipo,
		&i.Cores,
		&i.TipoConteudo,
		&i.UrlImagem,
		&i.TextoConteudo,
		&i.TextoFonte,
		&i.Lado,
		&i.Localizacao,
		&i.CanvasX,
		&i.CanvasY,
		&i.CanvasEscala,
		&i.CanvasRotacao,
		&i.CanvasLargura,
		&i.CanvasAltura,
		&i.Observacao,
		&i.DeletadoEm,
	)
	return i, err
}
