// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: produtos.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduto = `-- name: CreateProduto :one
INSERT INTO produtos (id, empresa_id, nome, descricao, url_imagem)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, empresa_id, nome, descricao, url_imagem, consumo_por_unidade, unidade_consumo, criado_em, atualizado_em, deletado_em
`

type CreateProdutoParams struct {
	ID        uuid.UUID      `json:"id"`
	EmpresaID uuid.UUID      `json:"empresa_id"`
	Nome      string         `json:"nome"`
	Descricao sql.NullString `json:"descricao"`
	UrlImagem sql.NullString `json:"url_imagem"`
}

func (q *Queries) CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error) {
	row := q.db.QueryRowContext(ctx, createProduto,
		arg.ID,
		arg.EmpresaID,
		arg.Nome,
		arg.Descricao,
		arg.UrlImagem,
	)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Descricao,
		&i.UrlImagem,
		&i.ConsumoPorUnidade,
		&i.UnidadeConsumo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteProduto = `-- name: DeleteProduto :exec
UPDATE produtos SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteProdutoParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteProduto(ctx context.Context, arg DeleteProdutoParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduto, arg.ID, arg.EmpresaID)
	return err
}

const getProduto = `-- name: GetProduto :one
SELECT id, empresa_id, nome, descricao, url_imagem, consumo_por_unidade, unidade_consumo, criado_em, atualizado_em, deletado_em
FROM produtos
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetProduto(ctx context.Context, id uuid.UUID) (Produto, error) {
	row := q.db.QueryRowContext(ctx, getProduto, id)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Descricao,
		&i.UrlImagem,
		&i.ConsumoPorUnidade,
		&i.UnidadeConsumo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listProdutos = `-- name: ListProdutos :many
SELECT id, empresa_id, nome, descricao, url_imagem, consumo_por_unidade, unidade_consumo, criado_em, atualizado_em, deletado_em
FROM produtos
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY nome
`

func (q *Queries) ListProdutos(ctx context.Context, empresaID uuid.UUID) ([]Produto, error) {
	rows, err := q.db.QueryContext(ctx, listProdutos, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Produto
	for rows.Next() {
		var i Produto
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Descricao,
			&i.UrlImagem,
			&i.ConsumoPorUnidade,
			&i.UnidadeConsumo,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduto = `-- name: UpdateProduto :one
UPDATE produtos
SET nome = $2, descricao = $3, url_imagem = $4, consumo_por_unidade = $5, unidade_consumo = $6, atualizado_em = NOW()
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, descricao, url_imagem, consumo_por_unidade, unidade_consumo, criado_em, atualizado_em, deletado_em
`

type UpdateProdutoParams struct {
	ID               uuid.UUID       `json:"id"`
	Nome             string          `json:"nome"`
	Descricao        sql.NullString  `json:"descricao"`
	UrlImagem        sql.NullString  `json:"url_imagem"`
	ConsumoPorUnidade sql.NullFloat64 `json:"consumo_por_unidade"`
	UnidadeConsumo   sql.NullString  `json:"unidade_consumo"`
}

func (q *Queries) UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error) {
	row := q.db.QueryRowContext(ctx, updateProduto,
		arg.ID,
		arg.Nome,
		arg.Descricao,
		arg.UrlImagem,
		arg.ConsumoPorUnidade,
		arg.UnidadeConsumo,
	)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Descricao,
		&i.UrlImagem,
		&i.ConsumoPorUnidade,
		&i.UnidadeConsumo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
