// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: producao.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO configs_etapa_producao (id, empresa_id, nome, ordem, percentual_tempo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, empresa_id, nome, ordem, percentual_tempo, criado_em, deletado_em
`

type CreateConfigParams struct {
	ID              uuid.UUID     `json:"id"`
	EmpresaID       uuid.UUID     `json:"empresa_id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
}

type CreateConfigRow struct {
	ID              uuid.UUID     `json:"id"`
	EmpresaID       uuid.UUID     `json:"empresa_id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
	CriadoEm        sql.NullTime  `json:"criado_em"`
	DeletadoEm      sql.NullTime  `json:"deletado_em"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (CreateConfigRow, error) {
	row := q.db.QueryRowContext(ctx, createConfig,
		arg.ID,
		arg.EmpresaID,
		arg.Nome,
		arg.Ordem,
		arg.PercentualTempo,
	)
	var i CreateConfigRow
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Ordem,
		&i.PercentualTempo,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const createEtapa = `-- name: CreateEtapa :one
INSERT INTO etapas_producao (id, ordem_producao_id, config_etapa_id, status, responsavel, previsao_conclusao)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ordem_producao_id, config_etapa_id, status, responsavel, previsao_conclusao, data_inicio, iniciado_em, data_conclusao, finalizado_em, deletado_em
`

type CreateEtapaParams struct {
	ID                uuid.UUID      `json:"id"`
	OrdemProducaoID   uuid.UUID      `json:"ordem_producao_id"`
	ConfigEtapaID     uuid.UUID      `json:"config_etapa_id"`
	Status            sql.NullString `json:"status"`
	Responsavel       uuid.NullUUID  `json:"responsavel"`
	PrevisaoConclusao sql.NullTime   `json:"previsao_conclusao"`
}

func (q *Queries) CreateEtapa(ctx context.Context, arg CreateEtapaParams) (EtapasProducao, error) {
	row := q.db.QueryRowContext(ctx, createEtapa,
		arg.ID,
		arg.OrdemProducaoID,
		arg.ConfigEtapaID,
		arg.Status,
		arg.Responsavel,
		arg.PrevisaoConclusao,
	)
	var i EtapasProducao
	err := row.Scan(
		&i.ID,
		&i.OrdemProducaoID,
		&i.ConfigEtapaID,
		&i.Status,
		&i.Responsavel,
		&i.PrevisaoConclusao,
		&i.DataInicio,
		&i.IniciadoEm,
		&i.DataConclusao,
		&i.FinalizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const createOrdem = `-- name: CreateOrdem :one
INSERT INTO ordens_producao (id, empresa_id, pedido_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, empresa_id, pedido_id, status, iniciado_em, finalizado_em, criado_em, deletado_em
`

type CreateOrdemParams struct {
	ID        uuid.UUID      `json:"id"`
	EmpresaID uuid.UUID      `json:"empresa_id"`
	PedidoID  uuid.UUID      `json:"pedido_id"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) CreateOrdem(ctx context.Context, arg CreateOrdemParams) (OrdensProducao, error) {
	row := q.db.QueryRowContext(ctx, createOrdem,
		arg.ID,
		arg.EmpresaID,
		arg.PedidoID,
		arg.Status,
	)
	var i OrdensProducao
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.Status,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteConfig = `-- name: DeleteConfig :exec
UPDATE configs_etapa_producao SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteConfigParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteConfig(ctx context.Context, arg DeleteConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, arg.ID, arg.EmpresaID)
	return err
}

const deleteOrdem = `-- name: DeleteOrdem :exec
UPDATE ordens_producao SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteOrdemParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteOrdem(ctx context.Context, arg DeleteOrdemParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrdem, arg.ID, arg.EmpresaID)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT id, empresa_id, nome, ordem, percentual_tempo, criado_em, deletado_em
FROM configs_etapa_producao
WHERE id = $1 AND deletado_em IS NULL
`

type GetConfigRow struct {
	ID              uuid.UUID     `json:"id"`
	EmpresaID       uuid.UUID     `json:"empresa_id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
	CriadoEm        sql.NullTime  `json:"criado_em"`
	DeletadoEm      sql.NullTime  `json:"deletado_em"`
}

func (q *Queries) GetConfig(ctx context.Context, id uuid.UUID) (GetConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i GetConfigRow
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Ordem,
		&i.PercentualTempo,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getEtapa = `-- name: GetEtapa :one
SELECT id, ordem_producao_id, config_etapa_id, status, responsavel, previsao_conclusao, data_inicio, iniciado_em, data_conclusao, finalizado_em, deletado_em
FROM etapas_producao
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetEtapa(ctx context.Context, id uuid.UUID) (EtapasProducao, error) {
	row := q.db.QueryRowContext(ctx, getEtapa, id)
	var i EtapasProducao
	err := row.Scan(
		&i.ID,
		&i.OrdemProducaoID,
		&i.ConfigEtapaID,
		&i.Status,
		&i.Responsavel,
		&i.PrevisaoConclusao,
		&i.DataInicio,
		&i.IniciadoEm,
		&i.DataConclusao,
		&i.FinalizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getOrdem = `-- name: GetOrdem :one
SELECT id, empresa_id, pedido_id, status, iniciado_em, finalizado_em, criado_em, deletado_em
FROM ordens_producao
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetOrdem(ctx context.Context, id uuid.UUID) (OrdensProducao, error) {
	row := q.db.QueryRowContext(ctx, getOrdem, id)
	var i OrdensProducao
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.Status,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, empresa_id, nome, ordem, percentual_tempo, criado_em, deletado_em
FROM configs_etapa_producao
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY ordem
`

type ListConfigsRow struct {
	ID              uuid.UUID     `json:"id"`
	EmpresaID       uuid.UUID     `json:"empresa_id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
	CriadoEm        sql.NullTime  `json:"criado_em"`
	DeletadoEm      sql.NullTime  `json:"deletado_em"`
}

func (q *Queries) ListConfigs(ctx context.Context, empresaID uuid.UUID) ([]ListConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfigsRow
	for rows.Next() {
		var i ListConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Ordem,
			&i.PercentualTempo,
			&i.CriadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEtapas = `-- name: ListEtapas :many
SELECT id, ordem_producao_id, config_etapa_id, status, responsavel, previsao_conclusao, data_inicio, iniciado_em, data_conclusao, finalizado_em, deletado_em
FROM etapas_producao
WHERE ordem_producao_id = $1 AND deletado_em IS NULL
`

func (q *Queries) ListEtapas(ctx context.Context, ordemProducaoID uuid.UUID) ([]EtapasProducao, error) {
	rows, err := q.db.QueryContext(ctx, listEtapas, ordemProducaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EtapasProducao
	for rows.Next() {
		var i EtapasProducao
		if err := rows.Scan(
			&i.ID,
			&i.OrdemProducaoID,
			&i.ConfigEtapaID,
			&i.Status,
			&i.Responsavel,
			&i.PrevisaoConclusao,
			&i.DataInicio,
			&i.IniciadoEm,
			&i.DataConclusao,
			&i.FinalizadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdens = `-- name: ListOrdens :many
SELECT id, empresa_id, pedido_id, status, iniciado_em, finalizado_em, criado_em, deletado_em
FROM ordens_producao
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY criado_em DESC
`

func (q *Queries) ListOrdens(ctx context.Context, empresaID uuid.UUID) ([]OrdensProducao, error) {
	rows, err := q.db.QueryContext(ctx, listOrdens, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdensProducao
	for rows.Next() {
		var i OrdensProducao
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.PedidoID,
			&i.Status,
			&i.IniciadoEm,
			&i.FinalizadoEm,
			&i.CriadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE configs_etapa_producao
SET nome = $2, ordem = $3, percentual_tempo = $4
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, ordem, percentual_tempo, criado_em, deletado_em
`

type UpdateConfigParams struct {
	ID              uuid.UUID     `json:"id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
}

type UpdateConfigRow struct {
	ID              uuid.UUID     `json:"id"`
	EmpresaID       uuid.UUID     `json:"empresa_id"`
	Nome            string        `json:"nome"`
	Ordem           int32         `json:"ordem"`
	PercentualTempo sql.NullInt32 `json:"percentual_tempo"`
	CriadoEm        sql.NullTime  `json:"criado_em"`
	DeletadoEm      sql.NullTime  `json:"deletado_em"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (UpdateConfigRow, error) {
	row := q.db.QueryRowContext(ctx, updateConfig,
		arg.ID,
		arg.Nome,
		arg.Ordem,
		arg.PercentualTempo,
	)
	var i UpdateConfigRow
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Ordem,
		&i.PercentualTempo,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const updateEtapaStatus = `-- name: UpdateEtapaStatus :one
UPDATE etapas_producao
SET status = $2, iniciado_em = CASE WHEN $2::text = 'em_andamento' AND iniciado_em IS NULL THEN NOW() ELSE iniciado_em END, finalizado_em = CASE WHEN $2::text = 'concluido' THEN NOW() ELSE finalizado_em END, data_conclusao = CASE WHEN $2::text = 'concluido' THEN NOW() ELSE data_conclusao END
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, ordem_producao_id, config_etapa_id, status, responsavel, previsao_conclusao, data_inicio, iniciado_em, data_conclusao, finalizado_em, deletado_em
`

type UpdateEtapaStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateEtapaStatus(ctx context.Context, arg UpdateEtapaStatusParams) (EtapasProducao, error) {
	row := q.db.QueryRowContext(ctx, updateEtapaStatus, arg.ID, arg.Status)
	var i EtapasProducao
	err := row.Scan(
		&i.ID,
		&i.OrdemProducaoID,
		&i.ConfigEtapaID,
		&i.Status,
		&i.Responsavel,
		&i.PrevisaoConclusao,
		&i.DataInicio,
		&i.IniciadoEm,
		&i.DataConclusao,
		&i.FinalizadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const updateOrdemStatus = `-- name: UpdateOrdemStatus :one
UPDATE ordens_producao
SET status = $2, iniciado_em = CASE WHEN $2::text = 'em_andamento' AND iniciado_em IS NULL THEN NOW() ELSE iniciado_em END, finalizado_em = CASE WHEN $2::text IN ('concluida', 'cancelada') THEN NOW() ELSE finalizado_em END
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, pedido_id, status, iniciado_em, finalizado_em, criado_em, deletado_em
`

type UpdateOrdemStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateOrdemStatus(ctx context.Context, arg UpdateOrdemStatusParams) (OrdensProducao, error) {
	row := q.db.QueryRowContext(ctx, updateOrdemStatus, arg.ID, arg.Status)
	var i OrdensProducao
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.PedidoID,
		&i.Status,
		&i.IniciadoEm,
		&i.FinalizadoEm,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
