// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error)
	CreateConfig(ctx context.Context, arg CreateConfigParams) (CreateConfigRow, error)
	CreateEmpresa(ctx context.Context, arg CreateEmpresaParams) (Empresa, error)
	CreateEtapa(ctx context.Context, arg CreateEtapaParams) (EtapasProducao, error)
	CreateItemPedido(ctx context.Context, arg CreateItemPedidoParams) (ItensPedido, error)
	CreateMateriaPrima(ctx context.Context, arg CreateMateriaPrimaParams) (MateriasPrima, error)
	CreateModelo(ctx context.Context, arg CreateModeloParams) (Modelo, error)
	CreateOrdem(ctx context.Context, arg CreateOrdemParams) (OrdensProducao, error)
	CreatePedido(ctx context.Context, arg CreatePedidoParams) (Pedido, error)
	CreatePersonalizacao(ctx context.Context, arg CreatePersonalizacaoParams) (Personalizaco, error)
	CreateProduto(ctx context.Context, arg CreateProdutoParams) (Produto, error)
	CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error)
	CreateVersaoItem(ctx context.Context, arg CreateVersaoItemParams) (VersoesItemPedido, error)
	DeleteCliente(ctx context.Context, arg DeleteClienteParams) error
	DeleteConfig(ctx context.Context, arg DeleteConfigParams) error
	DeleteEmpresa(ctx context.Context, id uuid.UUID) error
	DeleteItemPedido(ctx context.Context, arg DeleteItemPedidoParams) error
	DeleteMateriaPrima(ctx context.Context, arg DeleteMateriaPrimaParams) error
	DeleteModelo(ctx context.Context, arg DeleteModeloParams) error
	DeleteOrdem(ctx context.Context, arg DeleteOrdemParams) error
	DeletePedido(ctx context.Context, arg DeletePedidoParams) error
	DeletePersonalizacao(ctx context.Context, arg DeletePersonalizacaoParams) error
	DeleteProduto(ctx context.Context, arg DeleteProdutoParams) error
	DeleteUsuario(ctx context.Context, arg DeleteUsuarioParams) error
	GetCliente(ctx context.Context, id uuid.UUID) (Cliente, error)
	GetClienteByErpID(ctx context.Context, arg GetClienteByErpIDParams) (Cliente, error)
	GetConfig(ctx context.Context, id uuid.UUID) (GetConfigRow, error)
	GetEmpresa(ctx context.Context, id uuid.UUID) (Empresa, error)
	GetEmpresaBySlug(ctx context.Context, slug string) (Empresa, error)
	GetEtapa(ctx context.Context, id uuid.UUID) (EtapasProducao, error)
	GetItemPedido(ctx context.Context, id uuid.UUID) (ItensPedido, error)
	GetMateriaPrima(ctx context.Context, id uuid.UUID) (MateriasPrima, error)
	GetModelo(ctx context.Context, id uuid.UUID) (Modelo, error)
	GetOrdem(ctx context.Context, id uuid.UUID) (OrdensProducao, error)
	GetPedido(ctx context.Context, id uuid.UUID) (Pedido, error)
	GetPersonalizacao(ctx context.Context, id uuid.UUID) (Personalizaco, error)
	GetProduto(ctx context.Context, id uuid.UUID) (Produto, error)
	GetUltimaVersao(ctx context.Context, itemPedidoID uuid.UUID) (VersoesItemPedido, error)
	GetUsuario(ctx context.Context, id uuid.UUID) (Usuario, error)
	GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error)
	InitNumeroPedido(ctx context.Context, empresaID uuid.UUID) (int32, error)
	ListClientes(ctx context.Context, empresaID uuid.UUID) ([]Cliente, error)
	ListConfigs(ctx context.Context, empresaID uuid.UUID) ([]ListConfigsRow, error)
	ListEtapas(ctx context.Context, ordemProducaoID uuid.UUID) ([]EtapasProducao, error)
	ListItensPorPedido(ctx context.Context, pedidoID uuid.UUID) ([]ItensPedido, error)
	ListMateriasPrimas(ctx context.Context, empresaID uuid.UUID) ([]MateriasPrima, error)
	ListModelos(ctx context.Context, arg ListModelosParams) ([]Modelo, error)
	ListOrdens(ctx context.Context, empresaID uuid.UUID) ([]OrdensProducao, error)
	ListPedidos(ctx context.Context, empresaID uuid.UUID) ([]Pedido, error)
	ListPersonalizacoesPorItem(ctx context.Context, itemPedidoID uuid.UUID) ([]Personalizaco, error)
	ListProdutos(ctx context.Context, empresaID uuid.UUID) ([]Produto, error)
	ListUsuarios(ctx context.Context, empresaID uuid.UUID) ([]Usuario, error)
	ListVersoesPorItem(ctx context.Context, itemPedidoID uuid.UUID) ([]VersoesItemPedido, error)
	NextNumeroPedido(ctx context.Context, empresaID uuid.UUID) (int32, error)
	UpdateCliente(ctx context.Context, arg UpdateClienteParams) (Cliente, error)
	UpdateClienteErpID(ctx context.Context, arg UpdateClienteErpIDParams) (Cliente, error)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) (UpdateConfigRow, error)
	UpdateEmpresa(ctx context.Context, arg UpdateEmpresaParams) (Empresa, error)
	UpdateEtapaStatus(ctx context.Context, arg UpdateEtapaStatusParams) (EtapasProducao, error)
	UpdateItemPedido(ctx context.Context, arg UpdateItemPedidoParams) (ItensPedido, error)
	UpdateMateriaPrima(ctx context.Context, arg UpdateMateriaPrimaParams) (MateriasPrima, error)
	UpdateModelo(ctx context.Context, arg UpdateModeloParams) (Modelo, error)
	UpdateOrdemStatus(ctx context.Context, arg UpdateOrdemStatusParams) (OrdensProducao, error)
	UpdatePedidoStatus(ctx context.Context, arg UpdatePedidoStatusParams) (Pedido, error)
	UpdatePersonalizacao(ctx context.Context, arg UpdatePersonalizacaoParams) (Personalizaco, error)
	UpdateProduto(ctx context.Context, arg UpdateProdutoParams) (Produto, error)
	UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (Usuario, error)
}

var _ Querier = (*Queries)(nil)
