// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuarios.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (id, empresa_id, nome, email, perfil)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, empresa_id, nome, email, perfil, criado_em, deletado_em
`

type CreateUsuarioParams struct {
	ID        uuid.UUID      `json:"id"`
	EmpresaID uuid.UUID      `json:"empresa_id"`
	Nome      string         `json:"nome"`
	Email     string         `json:"email"`
	Perfil    sql.NullString `json:"perfil"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.ID,
		arg.EmpresaID,
		arg.Nome,
		arg.Email,
		arg.Perfil,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.Perfil,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
UPDATE usuarios SET deletado_em = NOW()
WHERE id = $1 AND empresa_id = $2 AND deletado_em IS NULL
`

type DeleteUsuarioParams struct {
	ID        uuid.UUID `json:"id"`
	EmpresaID uuid.UUID `json:"empresa_id"`
}

func (q *Queries) DeleteUsuario(ctx context.Context, arg DeleteUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, arg.ID, arg.EmpresaID)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, empresa_id, nome, email, perfil, criado_em, deletado_em
FROM usuarios
WHERE id = $1 AND deletado_em IS NULL
`

func (q *Queries) GetUsuario(ctx context.Context, id uuid.UUID) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.Perfil,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, empresa_id, nome, email, perfil, criado_em, deletado_em
FROM usuarios
WHERE email = $1 AND deletado_em IS NULL
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.Perfil,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id, empresa_id, nome, email, perfil, criado_em, deletado_em
FROM usuarios
WHERE empresa_id = $1 AND deletado_em IS NULL
ORDER BY nome
`

func (q *Queries) ListUsuarios(ctx context.Context, empresaID uuid.UUID) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios, empresaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.EmpresaID,
			&i.Nome,
			&i.Email,
			&i.Perfil,
			&i.CriadoEm,
			&i.DeletadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :one
UPDATE usuarios
SET nome = $2, perfil = $3
WHERE id = $1 AND deletado_em IS NULL
RETURNING id, empresa_id, nome, email, perfil, criado_em, deletado_em
`

type UpdateUsuarioParams struct {
	ID     uuid.UUID      `json:"id"`
	Nome   string         `json:"nome"`
	Perfil sql.NullString `json:"perfil"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, updateUsuario, arg.ID, arg.Nome, arg.Perfil)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.EmpresaID,
		&i.Nome,
		&i.Email,
		&i.Perfil,
		&i.CriadoEm,
		&i.DeletadoEm,
	)
	return i, err
}
