// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versoes.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createVersaoItem = `-- name: CreateVersaoItem :one
INSERT INTO versoes_item_pedido (id, item_pedido_id, numero_versao, snapshot, alterado_por)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_pedido_id, numero_versao, snapshot, alterado_por, criado_em
`

type CreateVersaoItemParams struct {
	ID           uuid.UUID       `json:"id"`
	ItemPedidoID uuid.UUID       `json:"item_pedido_id"`
	NumeroVersao int32           `json:"numero_versao"`
	Snapshot     json.RawMessage `json:"snapshot"`
	AlteradoPor  uuid.NullUUID   `json:"alterado_por"`
}

func (q *Queries) CreateVersaoItem(ctx context.Context, arg CreateVersaoItemParams) (VersoesItemPedido, error) {
	row := q.db.QueryRowContext(ctx, createVersaoItem,
		arg.ID,
		arg.ItemPedidoID,
		arg.NumeroVersao,
		arg.Snapshot,
		arg.AlteradoPor,
	)
	var i VersoesItemPedido
	err := row.Scan(
		&i.ID,
		&i.ItemPedidoID,
		&i.NumeroVersao,
		&i.Snapshot,
		&i.AlteradoPor,
		&i.CriadoEm,
	)
	return i, err
}

const getUltimaVersao = `-- name: GetUltimaVersao :one
SELECT id, item_pedido_id, numero_versao, snapshot, alterado_por, criado_em
FROM versoes_item_pedido
WHERE item_pedido_id = $1
ORDER BY numero_versao DESC
LIMIT 1
`

func (q *Queries) GetUltimaVersao(ctx context.Context, itemPedidoID uuid.UUID) (VersoesItemPedido, error) {
	row := q.db.QueryRowContext(ctx, getUltimaVersao, itemPedidoID)
	var i VersoesItemPedido
	err := row.Scan(
		&i.ID,
		&i.ItemPedidoID,
		&i.NumeroVersao,
		&i.Snapshot,
		&i.AlteradoPor,
		&i.CriadoEm,
	)
	return i, err
}

const listVersoesPorItem = `-- name: ListVersoesPorItem :many
SELECT id, item_pedido_id, numero_versao, snapshot, alterado_por, criado_em
FROM versoes_item_pedido
WHERE item_pedido_id = $1
ORDER BY numero_versao DESC
`

func (q *Queries) ListVersoesPorItem(ctx context.Context, itemPedidoID uuid.UUID) ([]VersoesItemPedido, error) {
	rows, err := q.db.QueryContext(ctx, listVersoesPorItem, itemPedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VersoesItemPedido
	for rows.Next() {
		var i VersoesItemPedido
		if err := rows.Scan(
			&i.ID,
			&i.ItemPedidoID,
			&i.NumeroVersao,
			&i.Snapshot,
			&i.AlteradoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
